Fix a bug that raise AttributeError.
When download attachment packages by using yum pkgmgr, the url
variable below is a unicode instead of SafeURL object.

Traceback (most recent call last):
......
  File "/home/huanghao/workspace/mic/plugins/imager/loop_plugin.py", line 127, in do_create
    creator.install()
  File "/usr/local/lib/python2.7/dist-packages/mic/imager/baseimager.py", line 1051, in install
    self.__attachment_packages(pkg_manager)
  File "/usr/local/lib/python2.7/dist-packages/mic/imager/baseimager.py", line 966, in __attachment_packages
    fpath = grabber.myurlgrab(url.full, fpath, proxies, None)
AttributeError: 'unicode' object has no attribute 'full'

Change-Id: Ib5c03ef053b8cf22f1b8ef1868ad244427df7cc6